extend-exclude = ["docs/references"]

[lint]
select = ["E", "F", "I", "UP"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"

[lint.isort]
known-first-party = ["falcon1_perception"]
